services:
  - type: web
    name: inventory-management
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: Inventory Management
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: inventory-management
          type: web
          property: host
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: inventory-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inventory-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: inventory-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: inventory-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: APP_KEY
        generateValue: true
    disk:
      name: inventory-storage
      mountPath: /var/www/storage
      sizeGB: 1

databases:
  - name: inventory-db
    databaseName: inventory
    plan: free 