services:
  - type: web
    name: rosels-trading
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health-check
    healthCheckTimeout: 100
    healthCheckInterval: 15s
    envVars:
      - key: PORT
        value: 10000
      - key: APP_NAME
        value: "Rosels Trading"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://inventory-management-k228.onrender.com
      - key: ASSET_URL
        value: https://inventory-management-k228.onrender.com
      - key: ASSET_URL_SECURE
        value: true
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: APP_KEY
        generateValue: true 